// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class DeviceLogDetail
{
    public long Id { get; set; }

    public long DeviceId { get; set; }

    public string RequestUrl { get; set; }

    public bool? ActiveFlag { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int SourceTypeId { get; set; }

    public virtual DeviceDetail Device { get; set; }

    public virtual ICollection<UserRequestPreference> UserRequestPreferences { get; set; } = new List<UserRequestPreference>();
}