// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class DeviceDetail
{
    public long Id { get; set; }

    public string DeviceIdentifier { get; set; }

    public string DeviceOs { get; set; }

    public string DeviceToken { get; set; }

    public long? UserId { get; set; }

    public bool? ActiveFlag { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<DeviceLogDetail> DeviceLogDetails { get; set; } = new List<DeviceLogDetail>();

    public virtual User User { get; set; }
}