// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class QuizParticipant
{
    public long Id { get; set; }

    public long SessionId { get; set; }

    public string Nickname { get; set; }

    public int? Score { get; set; }

    public decimal? Percentage { get; set; }

    public int? CorrectCount { get; set; }

    public int? TotalQuestions { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public long CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string DeviceId { get; set; }
}