// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class SharedQuizSession
{
    public long Id { get; set; }

    public long RequestId { get; set; }

    public long GeneratedBy { get; set; }

    public string ShareCode { get; set; }

    public string Title { get; set; }

    public bool? ActiveFlag { get; set; }

    public long CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}