// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class UserRequestPreference
{
    public long Id { get; set; }

    public long? RequestId { get; set; }

    public int? NumberOfQuestions { get; set; }

    public int? QuestionsTypeId { get; set; }

    public int? DifficultyTypeId { get; set; }

    public long? UserId { get; set; }

    public bool? ActiveFlag { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? LanguageId { get; set; }

    public virtual DeviceLogDetail Request { get; set; }

    public virtual User User { get; set; }
}