// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class UserRequestResponse
{
    public long Id { get; set; }

    public long RequestId { get; set; }

    public string QuestionJson { get; set; }

    public string FlashcardJson { get; set; }

    public string SummaryJson { get; set; }
}