// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vidyasetu_API.Models;

public partial class UserQuizeReponse
{
    public long Id { get; set; }

    public long RequestId { get; set; }

    public string Question { get; set; }

    public string UserAnswer { get; set; }

    public string TotalTimeTaken { get; set; }
}